### ISSUE TITLE
user friendly database installation

### ISSUE THREAD

**Issue by cedriclange** [lemondropsarl/webase#1]
User can't install easily the app at first run

at first run the user can can fill a form to install the  database and admin user

**Comment by cedriclange** [comment]
the process in under progress and should be shipped soon

**Comment by cedriclange** [comment]
@Arcenebeya will you be able to work on cleanning the UI?

**Comment by Arcenebeya** [comment]
Yes @cedriclange , I ll make it, but please just guide me on how you would like it to look like. thanks!
