### ISSUE TITLE
Add unit test

### ISSUE THREAD

**Issue by oesukam** [lemondropsarl/webase#4]
**Describe the bug**
It will be better to have enough test cases to bring a feature breaking existing feature when making changes

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cedriclange** [comment]
what's the best approach @oesukam ? because webase is modular...then each modules can contains his own testcase...
instead of putting in the application folder

**Comment by cedriclange** [comment]
unit testing has been added 
run test with : `vendor/bin/phpunit -c application/tests/`

or adding future testcase following example of `dahsboard`

**Comment by cedriclange** [comment]
this issue is done successfully the develop branch build successfully with Travis
![build result](https://user-images.githubusercontent.com/22542802/78332439-4f05be80-7588-11ea-9893-676e0ccd2337.gif)
